/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-library-conventions")
}
// plugins {
//     // Apply the Java Library plugin
//     java
// }

repositories {
    // Add Maven Central repository for dependencies
    mavenCentral()
}

dependencies {
    // Add Hyperledger Fabric SDK dependency
    implementation("org.hyperledger.fabric-sdk-java:fabric-sdk-java:2.2.0") // Adjust version as needed
}

java {
    // Set Java source and target compatibility
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}
